name: Django Tests
permissions:
  contents: read
  checks: write
  pull-requests: write

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          src: "./backend"

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Ensure test directories have appropriate permissions for writing
        run: |
          mkdir -p ./backend/artifacts/test-reports
          chmod 777 ./backend/artifacts/test-reports
          chmod 777 ./backend/provider_directory/static

      - name: Setup test environment
        run: |
          make test-setup

      - name: Run tests
        run: |
          make test-backend

      - name: Upload test results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: backend/artifacts/test-reports/*.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          check_name: "Backend Django Test Results"
          comment_mode: changes in failures
          files: |
            backend/artifacts/test-reports/*.xml
