name: Spellcheck
permissions:
  contents: read
  checks: write
  pull-requests: write

on:
  pull_request:

jobs:
  typos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install typos
        uses: crate-ci/typos@v1.29.5

      - name: Run typos with reviewdog
        uses: reviewdog/action-reviewdog@v1
        with:
          reporter: github-pr-review
          tool_name: typos
          level: warning
          filter_mode: diff_context
          fail_on_error: false
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}